apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-azure-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-azure
  template:
    metadata:
      labels:
        app: python-azure
    spec:
      containers:
      - name: python-azure
        image: <seu-registro>.azurecr.io/python-azure:latest
        ports:
        - containerPort: 3000
